name: Check Docker Hub Tags, Build and Push
on:
  schedule:
    - cron: '0 2,14 * * *'  # Runs daily at 2 AM and 2 PM
  workflow_dispatch:  # Allows manual triggering
jobs:
  check-tags:
    runs-on: ubuntu-latest
    outputs:
      build_28_apache: ${{ steps.check_tags.outputs.build_28_apache }}
      build_27_apache: ${{ steps.check_tags.outputs.build_27_apache }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all branches
    - name: Check Docker Hub for tag updates
      id: check_tags
      run: |
        # Define Docker Hub repository details
        REPO="library/nextcloud"
        
        # Fetch the latest tags from Docker Hub
        curl -s "https://hub.docker.com/v2/namespaces/library/repositories/nextcloud/tags?page_size=100" -o tags.json
        # Define the current date and 24 hours ago date
        CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        DATE_24_HOURS_AGO=$(date -u -d '24 hours ago' +"%Y-%m-%dT%H:%M:%SZ")
        # Function to extract and compare tag timestamps
        compare_tag_time() {
          local tag_last_updated=$1
          # Remove microseconds (.038463) and 'Z'
          tag_last_updated=$(echo $tag_last_updated | sed -e 's/\.[0-9]*Z/Z/')
          # Compare with the 24 hours ago date
          if [[ "$(date -d "$tag_last_updated" +%s)" -gt "$(date -d "$DATE_24_HOURS_AGO" +%s)" ]]; then
            echo "true"
          else
            echo "false"
          fi
        }
        # Extract last updated dates for tags and check for changes
        LAST_UPDATE_28_APACHE=$(jq -r '.results[] | select(.name=="28-apache") | .last_updated' tags.json)
        LAST_UPDATE_27_APACHE=$(jq -r '.results[] | select(.name=="27-apache") | .last_updated' tags.json)
        # Check if the tags were updated in the last 24 hours
        BUILD_28_APACHE=$(compare_tag_time "$LAST_UPDATE_28_APACHE")
        BUILD_27_APACHE=$(compare_tag_time "$LAST_UPDATE_27_APACHE")
        # Set the outputs for future jobs
        echo "build_28_apache=$BUILD_28_APACHE" >> $GITHUB_OUTPUT
        echo "build_27_apache=$BUILD_27_APACHE" >> $GITHUB_OUTPUT
  build-master:
    needs: check-tags
    if: needs.check-tags.outputs.build_28_apache == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push Docker Image for master branch
      run: |
        docker buildx build --push -t cardonaje/nextcloud:28-apache .
        docker buildx build --push -t cardonaje/nextcloud:latest .
  build-nextcloud27:
    needs: check-tags
    if: needs.check-tags.outputs.build_27_apache == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout nextcloud27 branch
      uses: actions/checkout@v4
      with:
        ref: nextcloud27
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push Docker Image for nextcloud27 branch
      run: |
        docker buildx build --push -t cardonaje/nextcloud:27-apache .
