name: Docker Image CI

on:
  push:
    branches:
      - master
      - nextcloud26
      - nextcloud27
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to build'
        required: true
        default: 'main'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        # Determine the branch name to use for the image tag
        if [ "${{ github.event_name }}" = "push" ]; then
          IMAGE_TAG=${{ github.ref_name }}
        else
          IMAGE_TAG=${{ github.event.inputs.branch }}
        fi
        docker build -t cardonaje/nextcloud:${IMAGE_TAG} .
        docker push cardonaje/nextcloud:${IMAGE_TAG}
